services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./MarketDataApi
    ports:
      - "5091:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Brapi__BaseUrl=https://brapi.dev/api
      - Brapi__BrapiApiKey=${BRAPI_API_KEY}
      - MarketBrain__BaseUrl=http://brain:8000
    depends_on:
      db:
        condition: service_healthy
      brain:
        condition: service_started

  brain:
    build: 
      context: ./MarketBrain

    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

    expose:
      - "8000"

  dashboard:
    build: ./MarketDashboard
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api

  cache:
    image: redis:7-alpine
    expose:
      - "6379"

volumes:
  postgres_data: