// <auto-generated />
using System;
using MarketDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketDataApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608004610_AddFundamentalsTable")]
    partial class AddFundamentalsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketDataApi.Models.FundamentalRecord", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cagr5y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DebtToEbitda")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("numeric");

                    b.Property<string>("FiiType")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("NetMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceToBook")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceToEarnings")
                        .HasColumnType("numeric");

                    b.Property<int?>("PropertiesCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Roe")
                        .HasColumnType("numeric");

                    b.Property<string>("SectorOrSegment")
                        .HasColumnType("text");

                    b.Property<decimal?>("ShareholdersCount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Vacancy")
                        .HasColumnType("numeric");

                    b.HasKey("Ticker");

                    b.ToTable("Fundamentals");
                });

            modelBuilder.Entity("MarketDataApi.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SearchLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
