// <auto-generated />
using System;
using MarketDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketDataApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616012942_AddUserPortfolios")]
    partial class AddUserPortfolios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketDataApi.Models.FundamentalRecord", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DailyLiquidity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DebtToEbitda")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EvEbit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EvEbitda")
                        .HasColumnType("numeric");

                    b.Property<string>("FiiType")
                        .HasColumnType("text");

                    b.Property<decimal?>("LastDividend")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetWorth")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceToBook")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceToEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProfitCagr5y")
                        .HasColumnType("numeric");

                    b.Property<int?>("PropertiesCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RevenueCagr5y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Roe")
                        .HasColumnType("numeric");

                    b.Property<string>("SectorOrSegment")
                        .HasColumnType("text");

                    b.Property<decimal?>("ShareholdersCount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Vacancy")
                        .HasColumnType("numeric");

                    b.HasKey("Ticker");

                    b.ToTable("Fundamentals");
                });

            modelBuilder.Entity("MarketDataApi.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("MarketDataApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarketDataApi.Models.UserAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssets");
                });

            modelBuilder.Entity("MarketDataApi.Models.UserAsset", b =>
                {
                    b.HasOne("MarketDataApi.Models.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketDataApi.Models.User", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
